backend:
  name: git-gateway
  branch: dev # Branch to update (optional; defaults to master)
media_folder: "uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "uploads" # The src attribute for uploaded media will begin with /images/uploa
collections:
- name: "blog" # Used in routes, e.g., /admin/collections/blog
  label: "Blog" # Used in the UI
  folder: "content/blog" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields: # The fields for each document, usually in front matter
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Featured Image", name: "featuredImage", widget: "image"}
    - {label: "Body", name: "body", widget: "markdown"}
    - label: "Gallery"
      name: "galleryImages"
      widget: "list"
      fields: 
        - {label: "Link", name: "src", widget: "string"}
        - {label: "Alt", name: "alt", widget: "string"}
        - {label: "Image", name: "image", widget: "image"}
    - label: "Post Other"
      name: "otherTitle"
      widget: "relation"
      collection: "blog"
      searchFields: ["title"]
      valueField: "featuredImage"
      displayFields: ["title", "featuredImage"]
      collections:
- name: "conf" # Used in routes, e.g., /admin/collections/blog
  label: "Conference Page" # Used in the UI
  folder: "content/conf" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields: # The fields for each document, usually in front matter
    - {label: "Title", name: "title", widget: "string"}
    - label: "Conference Date"
      name: "startDate"
      widget: "datetime"
      default: ''
      format: "LLLL"
      required: false
    - label: "Nav Menu"
      name: "nav"
      widget: "relation"
      collection: "nav"
      searchFields: ["title"]
      valueField: "data"
      displayFields: ["title"]
    - label: "Hero"
      name: "hero"
      widget: "object"
      fields:
      - {label: "Title", name: "title", widget: "string", required: false, default: ''}
      - {label: "Sub title", name: "subtitle", widget: "string", required: false, default: ''}
      - {label: "Image", name: "image", widget: "image", required: false, default: ''}
      - {label: "Image Portrait", name: "imagePt", widget: "image", required: false, default: ''}
      - label: "Button"
        name: "button"
        widget: "object"
        fields:
        - {label: "Title", name: "title", widget: "string", required: false, default: ''}
        - {label: "link", name: "link", widget: "string", required: false, default: ''}
    - label: "About"
      name: "about"
      widget: "object"
      fields:
        - {label: "Section ID", name: "id", widget: "string", required: false, default: ''}
        - {label: "Title", name: "title", widget: "string", required: false, default: ''}
        - {label: "Paragraph", name: "paragraph", widget: "markdown", required: false, default: ''}
        - {label: "logo", name: "logo", widget: "image", required: false, default: ''}
        - {label: "Button Title", name: "linkTitle", widget: "string", required: false, default: ''}
        - {label: "Button Link", name: "link", widget: "string", required: false, default: ''}
    - label: "Stat"
      name: "stat"
      widget: "object"
      fields:
        - {label: "Section ID", name: "id", widget: "string", required: false, default: ''}
        - {label: "Background", name: "image", widget: "image", required: false, default: ''}
        - {label: "Backgound Portrait", name: "imagePt", widget: "image", required: false, default: ''}
        - label: "Items"
          name: "items"
          widget: "list"
          required: false
          default: ''
          fields:
          - {label: "Title", name: "title", widget: "string", required: false, default: ''}
          - {label: "Paragraph", name: "paragraph", widget: "markdown", required: false, default: ''}
    - label: "Media Tiles"
      name: "mediaTiles"
      widget: "object"
      default: ''
      required: false
      fields:
        - {label: "Title", name: "title", widget: "string", required: false, default: ''}
        - {label: "Subtitle", name: "subtitle", widget: "string", required: false, default: ''}
        - {label: "Section ID", name: "id", widget: "string", required: false, default: ''}
        - label: "Items"
          name: "items"
          widget: "list"
          fields: 
            - {label: "Title", name: "title", widget: "string"}
            - {label: "Active", name: "active", widget: "boolean", default: "true"}
            - label: "Type"
              name: "type"
              widget: "select"
              required: true
              default: "gallery"
              options:
                - {label: "Image/Video Gallary", value: "gallery", default: '', required: false}
                - {label: "Youtube Video", value: "youtube", default: '', required: false}
            - {label: "Link", name: "src", widget: "string", default: '', required: false}
            - {label: "Image", name: "image", widget: "image", default: '', required: false}
    - label: "Playlists"
      name: "playlists"
      widget: "object"
      default: ''
      required: false
      fields:
        - {label: "Title", name: "title", widget: "string", required: false, default: ''}
        - {label: "Subtitle", name: "subtitle", widget: "string", required: false, default: ''}
        - {label: "Section ID", name: "id", widget: "string", required: false, default: ''}
        - label: "Items"
          name: "items"
          widget: "list"
          fields: 
            - {label: "Title", name: "title", widget: "string"}
            - {label: "Active", name: "active", widget: "boolean", default: "true"}
            - label: "Type"
              name: "type"
              widget: "select"
              required: true
              default: "gallery"
              options:
                - {label: "Image/Video Gallary", value: "gallery", default: '', required: false}
                - {label: "Youtube Video", value: "youtube", default: '', required: false}
            - {label: "Link", name: "src", widget: "string", default: '', required: false}
            - {label: "Image", name: "image", widget: "image", default: '', required: false}
- name: "nav" # Used in routes, e.g., /admin/collections/blog
  label: "Nav Menu" # Used in the UI
  folder: "content/nav" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields: # The fields for each document, usually in front matter
    - {label: "Title", name: "title", widget: "string"}
    - label: "Data"
      name: "data"
      widget: "object"
      fields:
      - label: "Nav Menu Items"
        name: "items"
        widget: "list"
        fields: 
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Link", name: "src", widget: "string"}
          - {label: "Active", name: "active", widget: "boolean", default: true}
      - label: "Social Icons"
        name: "socialicons"
        widget: "relation"
        collection: "socialicons"
        searchFields: ["title"]
        valueField: "data"
        required: false
        default: ''
        displayFields: ["title"] 
- name: "socialicons" # Used in routes, e.g., /admin/collections/blog
  label: "Social Icons" # Used in the UI
  folder: "content/socialicons" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields: # The fields for each document, usually in front matter
    - {label: "Title", name: "title", widget: "string"}
    - label: "Data"
      name: "data"
      widget: "object"
      required: false 
      default: ''
      fields:
      - label: "Social Icons"
        name: "items"
        widget: "list"
        fields: 
          - {label: "Title", name: "title", widget: "string", required: false, default: ''}
          - {label: "Link", name: "src", widget: "string", required: false, default: ''}
          - label: "Icon"
            name: "icon"
            widget: "select"
            required: true
            default: "icon-facebook-square"
            options:
              - { label: "icon-facebook-square", value: "icon-facebook-square"}      
              - { label: "icon-twitter", value: "icon-twitter"}
              - { label: "icon-youtube-play", value: "icon-youtube-play"}
              - { label: "icon-instagram", value: "icon-instagram"}
              - { label: "icon-github", value: "icon-github"}
              - { label: "icon-telegram", value: "icon-telegram"}
              - { label: "icon-phone", value: "icon-phone"}
              - { label: "icon-envelope", value: "icon-envelope"}
          - {label: "Active", name: "active", widget: "boolean", required: false, default: true}          